import { Command } from 'commander';
import { recoverMessageAddress, getAddress, isHex, size } from 'viem';
import { resolveSigner } from '../../wallet/signer.js';
import {
  makeSiweMessage,
  encodeToken,
  decodeToken,
  parseSiweMessage,
  readMessageInput,
  die,
} from './helpers.js';
import type { SiweFields, SiweTokenPayload } from './types.js';

export function makeSiweCommand(): Command {
  const cmd = new Command('siwe')
    .description(
      '[DEPRECATED] SIWE (Sign-In with Ethereum) token commands (prepare, encode, decode, verify, auth)\n\n' +
      'DEPRECATION REASON:\n' +
      'SIWE tokens generated by this command are signed by the wallet managed inside this CLI.\n' +
      'This means the authenticated identity is locked to this CLI\'s wallet — other clients\n' +
      '(e.g. a Web UI or mobile app) that hold a different wallet cannot prove the same identity,\n' +
      'even if they belong to the same user. Agents accepting these tokens will therefore see\n' +
      'different identities depending on which client is used, making multi-client scenarios impossible.\n\n' +
      'This command will be removed in a future version.',
    )
    .hook('preAction', () => {
      process.stderr.write(
        'Warning: `siwe` is deprecated and will be removed in a future version.\n' +
        'SIWE tokens are tied to this CLI\'s wallet and cannot be shared with other clients (Web UI, etc.).\n' +
        'Using this for authentication locks the identity to this wallet only.\n',
      );
    });

  // siwe prepare
  cmd
    .command('prepare')
    .description('Generate an unsigned EIP-4361 SIWE message for manual signing')
    .option('--address <address>', 'Ethereum address (skips wallet resolution if provided)')
    .requiredOption('--domain <host>', 'Domain (e.g. app.example.com)')
    .requiredOption('--uri <uri>', 'URI (e.g. https://app.example.com)')
    .option('--ttl <duration>', 'Expiration duration (30m, 1h, 7d)', '7d')
    .option('--chain-id <n>', 'EIP-155 chain ID', '1')
    .option('--statement <text>', 'Statement text', 'I accept the Terms of Service')
    .option('--wallet <name>', 'Local wallet to use (overrides default wallet)')
    .option('--custodial', 'Use the custodial wallet (overrides default wallet)')
    .option('--token <jwt>', 'JWT for custodial wallet (overrides config)')
    .option('--url <url>', 'Web app URL for this request only (overrides config)')
    .action(async (opts: {
      address?: string;
      domain: string;
      uri: string;
      ttl: string;
      chainId: string;
      statement: string;
      wallet?: string;
      custodial?: boolean;
      token?: string;
      url?: string;
    }) => {
      try {
        const address = opts.address
          ?? await resolveSigner({ wallet: opts.wallet, custodial: opts.custodial, token: opts.token, url: opts.url })
              .then((s) => s.getAddress())
              .catch((err: unknown) => { die(err instanceof Error ? err.message : String(err)); });

        let message: string;
        try {
          message = makeSiweMessage(
            address,
            opts.domain,
            opts.uri,
            opts.ttl,
            opts.statement,
            parseInt(opts.chainId, 10),
          );
        } catch (err) {
          die(err instanceof Error ? err.message : String(err));
        }
        console.log(message);
      } catch (err) {
        die(err instanceof Error ? err.message : String(err));
      }
    });

  // siwe encode
  cmd
    .command('encode')
    .description('Combine a SIWE message and its signature into a base64url token')
    .requiredOption('--signature <hex>', 'Signature hex')
    .option('--message-file <path>', 'Path to message file (default: stdin)')
    .action(async (opts: { signature: string; messageFile?: string }) => {
      if (!isHex(opts.signature) || size(opts.signature) !== 65) {
        die('--signature must be a 65-byte hex string starting with 0x');
      }
      let message: string;
      try {
        message = await readMessageInput(opts.messageFile);
      } catch (err) {
        die(err instanceof Error ? err.message : String(err));
      }
      const token = encodeToken(message.trimEnd(), opts.signature);
      console.log(token);
    });

  // siwe decode
  cmd
    .command('decode')
    .description('Decode and display the contents of a base64url SIWE token')
    .argument('<token>', 'base64url SIWE token')
    .option('--json', 'Output as JSON')
    .action((token: string, opts: { json?: boolean }) => {
      let decoded: SiweTokenPayload, fields: SiweFields;
      try {
        decoded = decodeToken(token);
        fields = parseSiweMessage(decoded.message);
      } catch (err) {
        return die(err instanceof Error ? err.message : String(err));
      }

      if (opts.json) {
        console.log(JSON.stringify({ ...fields, signature: decoded.signature }, null, 2));
        return;
      }

      const lines = [
        `Address:    ${fields.address}`,
        `Domain:     ${fields.domain}`,
        `Statement:  ${fields.statement}`,
        `URI:        ${fields.uri}`,
        `Chain ID:   ${fields.chainId}`,
        `Nonce:      ${fields.nonce}`,
        `Issued At:  ${fields.issuedAt}`,
        `Expires:    ${fields.expiresAt ?? '(none)'}`,
        `Signature:  ${decoded.signature}`,
      ];
      lines.forEach((l) => console.log(l));
    });

  // siwe verify
  cmd
    .command('verify')
    .description('Verify a SIWE token\'s signature and expiry, and print the recovered signer address')
    .argument('<token>', 'base64url SIWE token')
    .action(async (token: string) => {
      let decoded: SiweTokenPayload, fields: SiweFields;
      try {
        decoded = decodeToken(token);
        fields = parseSiweMessage(decoded.message);
      } catch (err) {
        return die(err instanceof Error ? err.message : String(err));
      }

      let recovered: string;
      try {
        recovered = await recoverMessageAddress({ message: decoded.message, signature: decoded.signature as `0x${string}` });
      } catch {
        return die('signature verification failed');
      }

      let expectedAddress: string;
      try {
        expectedAddress = getAddress(fields.address);
      } catch {
        return die('token contains invalid Ethereum address');
      }
      if (recovered !== expectedAddress) {
        die('signature mismatch');
      }

      if (fields.expiresAt) {
        const expiry = new Date(fields.expiresAt);
        if (isNaN(expiry.getTime())) {
          die('token has invalid expiration date');
        }
        if (expiry < new Date()) {
          die('token expired');
        }
      }

      console.log(recovered);
    });

  // siwe auth
  cmd
    .command('auth')
    .description('Generate, sign, and encode a SIWE token in one step using the active wallet')
    .requiredOption('--domain <host>', 'Domain')
    .requiredOption('--uri <uri>', 'URI')
    .option('--ttl <duration>', 'Expiration duration (30m, 1h, 7d)', '7d')
    .option('--chain-id <n>', 'EIP-155 chain ID', '1')
    .option('--statement <text>', 'Statement text', 'I accept the Terms of Service')
    .option('--wallet <name>', 'Local wallet to sign with (overrides default wallet)')
    .option('--custodial', 'Use the custodial wallet (overrides default wallet)')
    .option('--token <jwt>', 'JWT for custodial signing (overrides config)')
    .option('--url <url>', 'Web app URL for this request only (overrides config)')
    .option('--json', 'Output as JSON { token: "..." }')
    .action(async (opts: {
      domain: string;
      uri: string;
      ttl: string;
      chainId: string;
      statement: string;
      wallet?: string;
      custodial?: boolean;
      token?: string;
      url?: string;
      json?: boolean;
    }) => {
      try {
        const signer = await resolveSigner({ wallet: opts.wallet, custodial: opts.custodial, token: opts.token, url: opts.url });
        const address = await signer.getAddress();

        let message: string;
        try {
          message = makeSiweMessage(
            address,
            opts.domain,
            opts.uri,
            opts.ttl,
            opts.statement,
            parseInt(opts.chainId, 10),
          );
        } catch (err) {
          die(err instanceof Error ? err.message : String(err));
        }

        const signature = await signer.signMessage(message);
        const encoded = encodeToken(message.trimEnd(), signature);

        if (opts.json) {
          console.log(JSON.stringify({ token: encoded }, null, 2));
        } else {
          console.log(encoded);
        }
      } catch (err) {
        die(err instanceof Error ? err.message : String(err));
      }
    });

  return cmd;
}
